#Faça um programa que leia algo pelo teclado e mostre na tela o tipo primitivo e todas as informações possiveis 
var=input('escreva algo:')
print('O tipo primitivo é: ', type(var))
print('Só tem espaço? ', var.isspace())
print('É numerico? ', var.isnumeric())
print('É alfabetico? ', var.isalpha())
print('É alfanumerico? ', var.isalnum())
print('Está em maiusculo?', var.isupper())
print('Está em minusculo? ', var.islower())
print('Esta capitalizada? ', var.istitle())
